### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by drache42** [dlmcpaul/EnphaseCollector#56]
Looks like you've made a lot of improvement lately. It would be great if you push a new release and update the dockerhub image so we could get all the new goodies :)

**Comment by dlmcpaul** [comment]
Yes, I want to do that.

**Comment by dlmcpaul** [comment]
Release done.  It is a big release for those using the internal database.  There is a script builtin now to update it from V1 to V2 so it should all be automatic.
