### ISSUE TITLE
Is "excess" equal to what is being exported to the grid?

### ISSUE THREAD

**Issue by drache42** [dlmcpaul/EnphaseCollector#57]
I believe because of https://github.com/dlmcpaul/EnphaseCollector/issues/55 the database might be little incomplete. 
Does the `solar.excess` measurement track the amount of power I'm sending back to the grid? Or does it measure a combination of what I give back to the grid **and** charge the battery with?

**Comment by dlmcpaul** [comment]
Excess is the amount of solar left over after self consumption.  In the absence of a battery it should be what goes to the grid.

If there was a battery I am not sure if consumption rises when charging so excess would still be grid export or if I have to modify the calculation.
